#ifndef _FLASHDEFINITIONS_H_
#define _FLASHDEFINITIONS_H_

#include "stm32f10x_flash.h"
#include "core_cm3.h"


#define FLASH_BASE_ADDRESS ((uint32_t) 0x0801F000)

#define LOCK_FLASH_BANK() FLASH_LockBank1()
#define UNLOCK_FLASH_BANK() FLASH_UnlockBank1()
#define CLEAR_FLASH_FLAG(FLAG) FLASH_ClearFlag(FLAG)
#define ERASE_FLASH_PAGE(REFERENCE) FLASH_ErasePage((REFERENCE) + FLASH_BASE_ADDRESS)
#define READ_FLASH_WORD(REFERENCE) (*(__IO uint32_t*) ((REFERENCE) + FLASH_BASE_ADDRESS))
#define WRITE_FLASH_WORD(REFERENCE, DATA) FLASH_ProgramWord((REFERENCE) + FLASH_BASE_ADDRESS, DATA)


#endif /* _FLASHDEFINITIONS_H_ */
